# MaxVoting

In [1]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
import math
import numpy as np
from statistics import mode, mean

data = load_iris()

In [2]:
x = data.data[:,:2]
y = data.target

In [3]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [4]:
class1 = LogisticRegression()
class2 = DecisionTreeClassifier()
class3 = KNeighborsClassifier()

clas = class1.fit(x_train, y_train)
clas = class2.fit(x_train, y_train)
clas = class3.fit(x_train, y_train)

y_pred1 = class1.predict(x_test)
y_pred2 = class2.predict(x_test)
y_pred3 = class3.predict(x_test)

/home/saireddy/anaconda3/envs/my_env/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/saireddy/anaconda3/envs/my_env/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [5]:
y_pred_prob_1 = class1.predict_proba(x_test)
y_pred_prob_2 = class2.predict_proba(x_test)
y_pred_prob_3 = class3.predict_proba(x_test)

In [6]:
print(y_pred_prob_1[0])

print(np.argmax(y_pred_prob_1[0]))

[0.10839577 0.40353485 0.48806938]
2


In [7]:
li = np.array([], dtype=int)
system = input("Enter voting you need Hard or Soft :-")
if system == "Hard":
    for i in range(len(y_pred1)):
        mode_function = mode([y_pred1[i], y_pred2[i], y_pred3[i]])
        li = np.append(li, [mode_function])
elif system=="Soft":
    for i in range(len(y_pred_prob_1)):
        final_pred = (y_pred_prob_1[i]+y_pred_prob_2[i]+y_pred_prob_3[i])/3
        li = np.append(li, np.argmax(final_pred))
else:
    print("No Method in python")

Enter voting you need Hard or Soft :-Hard


In [8]:
li

array([1, 2, 0, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 1, 0, 0, 1, 1,
       0, 0, 2, 0, 0, 2, 1, 0])

In [9]:
from sklearn.metrics import accuracy_score
accuracy_score(li, y_test)

0.6

# Averaging

In [10]:
model1 = DecisionTreeClassifier()
model2 = KNeighborsClassifier()
model3= LogisticRegression()

model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

pred1=model1.predict(x_test)
pred2=model2.predict(x_test)
pred3=model3.predict(x_test)

final = np.array([], dtype=int)
for i in range(len(pred1)):
    final = np.append(final, round((pred1[i]+pred2[i]+pred3[i])/3))

/home/saireddy/anaconda3/envs/my_env/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/saireddy/anaconda3/envs/my_env/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [11]:
final.astype(int)

array([1, 2, 0, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 1, 0, 0, 1, 1,
       0, 0, 2, 0, 0, 2, 1, 0])

In [12]:
accuracy_score(final, y_test)

0.6

# Weightning Average

In [13]:
np.random.seed(555)
weight = np.random.random_sample((30,))

In [14]:
finalweight = np.array([])
for i in range(len(pred1)):
    finalweight = np.append(finalweight, round((pred1[i]*weight[i]+pred2[i]*weight[i]+pred3[i]*weight[i]))/3)

In [15]:
finalweight = finalweight.astype(int)
finalweight

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
accuracy_score(finalweight,y_test )

0.4666666666666667

In [17]:
#https://www.analyticsvidhya.com/blog/2018/06/comprehensive-guide-for-ensemble-models/
#https://www.toptal.com/machine-learning/ensemble-methods-machine-learning